### ISSUE TITLE
Importscripts is called even when option disabled

### ISSUE THREAD

**Issue by BenBrocka** [o10n-x/wordpress-pwa-optimization#5] opened 2018-06-06 19:12 UTC
Similar to issue #4, the importscripts option isn't properly disabled when unchecked. Leave a broken URL in the importscripts section while it's checked, then uncheck it and save and install the SW. You'll get an error that the broken URL is being called, because the SW is still attempting importscripts().

Only way to clear it is re-enable the box (I have to check then uncheck to get the JSON editor to open as well) then clear it manually before unchecking Import Scripts.

Note this still occurs even when Register Service Worker is completely disabled.

**Comment by optimalisatie** [comment] 2018-06-10 17:50
Hi BenBrocka,

Thanks a lot for reporting the issue!

The issue wasn't related to the Service Worker configuration. It was a small bug that occurred because the Service Worker was updated based on the old settings. If you would have saved the settings twice, the Service Worker would have been re-written correctly.

The issue is fixed in the latest update.

https://github.com/o10n-x/wordpress-pwa-optimization/releases/tag/0.0.30

**Closed by optimalisatie** 2018-06-10 17:50 UTC
